#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
FORCE=0
if [[ "${1:-}" == "--force" ]]; then FORCE=1; fi

if [[ -f "$ENV_FILE" && "$FORCE" -eq 0 ]] && grep -qE '^DISCORD_TOKEN=[^[:space:]]+$' "$ENV_FILE"; then
  echo '.envは既に設定済みです。再設定する場合は ./setup-env.sh --force を実行してください。'
  exit 0
fi

read_default() {
  local prompt="$1" default="$2" value
  read -r -p "$prompt [$default]: " value
  printf '%s' "${value:-$default}"
}

read -r -s -p 'Discord Bot Token（入力は表示されません）: ' token
printf '\n'
if [[ -z "$token" || "$token" =~ [[:space:]] ]]; then
  echo 'DISCORD_TOKENが空、または空白を含んでいます。' >&2
  exit 1
fi

guild="$(read_default '開発用Guild ID（不要なら空欄）' '')"
speaker="$(read_default 'VOICEVOX話者ID' '3')"
image="$(read_default 'VOICEVOX Dockerイメージ' 'voicevox/voicevox_engine:latest')"
memory="$(read_default 'Goメモリ上限' '128MiB')"
gogc="$(read_default 'Go GC比率' '50')"
ttl="$(read_default 'TTSキャッシュ保持期間' '168h')"
cache_max="$(read_default 'TTSキャッシュ上限（bytes）' '268435456')"
audio_max="$(read_default '1音声の上限（bytes）' '33554432')"

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by setup-env.sh. Do not commit this file.
DISCORD_TOKEN=$token
DISCORD_GUILD_ID=$guild
VOICEVOX_SPEAKER=$speaker
VOICEVOX_IMAGE=$image
GOMEMLIMIT=$memory
GOGC=$gogc
YOMIAGE_CACHE_TTL=$ttl
YOMIAGE_CACHE_MAX_BYTES=$cache_max
YOMIAGE_MAX_AUDIO_BYTES=$audio_max
EOF
chmod 600 "$ENV_FILE"
echo ".envを作成しました: $ENV_FILE"
echo '次に docker compose up -d --build を実行してください。'
