[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot
$envPath = Join-Path $PSScriptRoot '.env'
$consentLogPath = Join-Path $PSScriptRoot '.yomiage-consent.jsonl'
$licenseVersion = '2026-10-08'

function Read-Default([string]$Prompt, [string]$Default) {
    $value = Read-Host "$Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value.Trim()
}

function Read-RequiredSecret([string]$Prompt) {
    $secure = Read-Host $Prompt -AsSecureString
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        $value = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
    if ([string]::IsNullOrWhiteSpace($value) -or $value -match '\s') {
        throw 'DISCORD_TOKENが空、または空白を含んでいます。設定をやり直してください。'
    }
    return $value.Trim()
}

if ((Test-Path $envPath) -and -not $Force) {
    $existing = Get-Content $envPath -Raw
    if ($existing -match '(?m)^DISCORD_TOKEN=\S+' -and
        $existing -match '(?m)^YOMIAGE_LICENSE_ACCEPTED=true$' -and
        $existing -match "(?m)^YOMIAGE_LICENSE_VERSION=$licenseVersion$") {
        Write-Host '.envは既に設定済みです。再設定する場合は -Force を指定してください。' -ForegroundColor Yellow
        exit 0
    }
}

Write-Host '🗣️ Yomiage Keiryou v5.3.6 対話型設定' -ForegroundColor Cyan
Write-Host '📜 利用ルール確認' -ForegroundColor Cyan
Write-Host '✅ 個人利用・学習・改造・商用利用が可能です。' -ForegroundColor Green
Write-Host '✅ 友人・チーム・コミュニティ内で共有できます。' -ForegroundColor Green
Write-Host '⚠️ 自作発言・不特定多数への再配布は禁止です。' -ForegroundColor Yellow
Write-Host '❌ マルウェア・不正アクセス・情報窃取・詐欺目的は禁止です。' -ForegroundColor Red
Write-Host '詳細: https://github.com/inumabu/yomiage/blob/main/LICENSE' -ForegroundColor DarkGray
$agreement = Read-Host '同意する場合は AGREE と入力してください'
if ($agreement.Trim().ToUpperInvariant() -ne 'AGREE') {
    throw '利用ルールへの同意が確認できないため、設定を中止しました。'
}
Write-Host 'Discord Bot Tokenは画面に表示されません。' -ForegroundColor DarkGray
$token = Read-RequiredSecret 'Discord Bot Token'
$guild = Read-Default '開発用Guild ID（不要なら空欄）' ''
$speaker = Read-Default 'VOICEVOX話者ID' '3'
$image = Read-Default 'VOICEVOX Dockerイメージ' 'voicevox/voicevox_engine:latest'
$memory = Read-Default 'Goメモリ上限' '128MiB'
$gogc = Read-Default 'Go GC比率' '50'
$ttl = Read-Default 'TTSキャッシュ保持期間' '168h'
$cacheMax = Read-Default 'TTSキャッシュ上限（bytes）' '268435456'
$audioMax = Read-Default '1音声の上限（bytes）' '33554432'

$content = @"
# Generated by setup-env.ps1. Do not commit this file.
DISCORD_TOKEN=$token
DISCORD_GUILD_ID=$guild
VOICEVOX_SPEAKER=$speaker
VOICEVOX_IMAGE=$image
GOMEMLIMIT=$memory
GOGC=$gogc
YOMIAGE_CACHE_TTL=$ttl
YOMIAGE_CACHE_MAX_BYTES=$cacheMax
YOMIAGE_MAX_AUDIO_BYTES=$audioMax
YOMIAGE_LICENSE_ACCEPTED=true
YOMIAGE_LICENSE_VERSION=$licenseVersion
"@
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($envPath, $content, $utf8NoBom)
$log = [ordered]@{
    event = 'license_consent'
    accepted = $true
    license_version = $licenseVersion
    accepted_at = [DateTime]::UtcNow.ToString('o')
    source = 'setup-env.ps1'
} | ConvertTo-Json -Compress
[System.IO.File]::AppendAllText($consentLogPath, $log + [Environment]::NewLine, $utf8NoBom)
Write-Host ".envを作成しました: $envPath" -ForegroundColor Green
Write-Host "🧾 同意ログをローカル保存しました（個人情報・Tokenは記録しません）: $consentLogPath" -ForegroundColor Green
Write-Host '設定が完了しました。通常はリポジトリのルートへ戻り .\setup.ps1 -SkipEnv を実行してください。' -ForegroundColor Green
